version: '3.7'

services:

  application:
    container_name: trading-app
    build: .
    depends_on:
      - zookeeper
      - kafka
      - database
    ports:
      - "9090:8080"
    networks:
      - trading-network

  zookeeper:
    container_name: trading-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - trading-network

  kafka:
    container_name: trading-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - trading-network

  database:
    container_name: trading-db
    image: postgres
    restart: always
    ports:
      - 5436:5432
    env_file:
      - config/database/database.env
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - trading-network

volumes:
  database-data:

networks:
  trading-network:
    name: trading-network
